double *vector(int, int);
double **matrix(int,int,int,int);
double **convert_matrix(double *,int,int,int,int);
double *dvector(int, int);
double **dmatrix(int,int,int,int);
int *ivector(int, int);
int **imatrix(int,int,int,int);
double **submatrix(double **,int,int,int,int,int,int);
void free_vector(double *, int,int);
void free_dvector(double *,int,int);
void free_ivector(int *, int, int);
void free_matrix(double **, int, int, int, int);
void free_dmatrix(double **,int,int,int,int);
void free_imatrix(int **,int,int,int,int);
void free_submatrix(double **,int,int,int,int);
void free_convert_matrix(double **,int,int,int,int);
void nrerror(char *);
